### ISSUE TITLE
ES6 version with tagged template strings

### ISSUE THREAD

**Issue by a-x-** [floatdrop/pff#3]
```es6
pff(42)`some es6 string. %d!`
```

It might be cool and useful

**Comment by floatdrop** [comment]
@a-x- in es6 world you should use template strings:

```js
const a = 42;
`some es6 string ${a}`
```

They faster and highlighting supported by all editors.

**Comment by a-x-** [comment]
I know. And I don't like them because it reminds me PHP.

**Comment by a-x-** [comment]
There is `util.format` in node.js.

I want to split string template and expressions.

Another way with es6 do not write long expressions in the `${}` things but use short self-declarative variables.
